# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfPNqiRFsYbFUwRVryRDPr1fYE7aMrec
"""

import pandas as pd 
import numpy as np

data = pd.read_csv("/content/Bank_Personal_Loan_Modelling.csv")
data.head()

data.info()

data.nunique()

data.isnull().sum()

data.drop(['ID','ZIP Code'],axis =1,inplace = True)

data.columns

num_columns = ['Age','Experience','Income','Family','CCAvg','Mortgage']

cat_columns = ['Education','Personal Loan','Securities Account','CD Account','Online','CreditCard']

data[cat_columns]=data[cat_columns].astype('category')

data.info()

X=data.drop(['Personal Loan'],axis=1)
y=data['Personal Loan']

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(X,y)

import pickle

print('saving model as pkl file.......')
pickle.dump(lr, open('model.pkl','wb'))



model = pickle.load(open('model.pkl','rb'))

